fix synatx error

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -57,32 +57,35 @@ jobs:
         if: matrix.platform == 'ubuntu-latest'
         run: |
           docker run --rm -v "${{ github.workspace }}:/work" -w /work archlinux:latest bash -c "
-          pacman -Syu  --noconfirm curl git base-devel acpica dmidecode python &&
+          pacman -Syu --noconfirm curl git base-devel acpica dmidecode python &&
           useradd -m builduser &&
           echo 'builduser ALL=(ALL) NOPASSWD: ALL' >> /etc/sudoers &&
           chown -R builduser:builduser /work &&
 
           su - builduser -c '
+            set -e
             cd /work &&
             git clone https://aur.archlinux.org/yay.git &&
             cd yay &&
             makepkg -si --noconfirm &&
-            
+
             yay -S --noconfirm coreboot-utils chromium-ectool cbmem || true &&
 
             curl https://sh.rustup.rs -sSf | bash -s -- -y &&
             source \$HOME/.cargo/env &&
 
-            cd "$(find /work -type d -name "src-tauri" -print -quit)" || { echo "src-tauri not found"; exit 1; } &&
+            tauri_path=\$(find /work -type d -name \"src-tauri\" -print -quit) &&
+            cd \"\$tauri_path\" || { echo \"src-tauri not found\"; exit 1; } &&
+
             mkdir -p target/release/bundle/arch/ &&
-            pwd &&
-            cp target/release/bundle/deb/*.deb target/release/bundle/arch &&
-            cp tauri.conf.json target/release/bundle/arch &&
-            cp -r /work/arch/* target/release/bundle/arch/ &&
+            cp target/release/bundle/deb/*.deb target/release/bundle/arch/ || true &&
+            cp tauri.conf.json target/release/bundle/arch/ || true &&
+            cp -r /work/arch/* target/release/bundle/arch/ || true &&
 
             cd target/release/bundle/arch &&
             makepkg -sf --noconfirm
-          '"
+          ' "
+
 
       - name: Upload Artifacts
         uses: actions/upload-artifact@v4
